"""empty message

Revision ID: 343df9ced978
Revises: af7e509c9f18
Create Date: 2025-04-16 17:09:01.202556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343df9ced978'
down_revision = 'af7e509c9f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('peak_hours', sa.Boolean(), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_consumption')
    # ### end Alembic commands ###
