"""empty message

Revision ID: 56991a87e963
Revises: 6b562a354979
Create Date: 2025-03-01 15:09:33.474450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56991a87e963'
down_revision = '6b562a354979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projects_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('goals_habits_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['projects_id'], ['id'])
        batch_op.drop_column('habits_id')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'goals', ['goals_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projects_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'projects', ['projects_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_goals_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('projects_notes_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('projects_habits_id_fkey', type_='foreignkey')
        batch_op.drop_column('notes_id')
        batch_op.drop_column('goals_id')
        batch_op.drop_column('habits_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habits_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('goals_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notes_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('projects_habits_id_fkey', 'habits', ['habits_id'], ['id'])
        batch_op.create_foreign_key('projects_notes_id_fkey', 'notes', ['notes_id'], ['id'])
        batch_op.create_foreign_key('projects_goals_id_fkey', 'goals', ['goals_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('projects_id')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goals_id')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habits_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('goals_habits_id_fkey', 'habits', ['habits_id'], ['id'])
        batch_op.drop_column('projects_id')

    # ### end Alembic commands ###
