"""empty message

Revision ID: 60c91321df87
Revises: 1a2565240ff7
Create Date: 2025-03-03 09:00:46.823782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c91321df87'
down_revision = '1a2565240ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=False))
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
