"""empty message

Revision ID: 613831a41de6
Revises: 98106162c729
Create Date: 2025-03-09 17:58:25.993335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613831a41de6'
down_revision = '98106162c729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('team_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
