"""empty message

Revision ID: 71b1ed309542
Revises: c7d4a8943dab
Create Date: 2025-03-02 09:32:11.462283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b1ed309542'
down_revision = 'c7d4a8943dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smartphones_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'smartphones', ['smartphones_id'], ['smartphone_id'])

    with op.batch_alter_table('smartphones', schema=None) as batch_op:
        batch_op.drop_constraint('smartphones_cart_id_fkey', type_='foreignkey')
        batch_op.drop_column('cart_id')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smartphones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('smartphones_cart_id_fkey', 'cart', ['cart_id'], ['cart_id'])

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('smartphones_id')

    # ### end Alembic commands ###
