"""empty message

Revision ID: 7b0104ace168
Revises: a9b7f08f1a62
Create Date: 2025-03-07 22:43:54.218242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0104ace168'
down_revision = 'a9b7f08f1a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('pathologies',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('pathologies',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
