"""empty message

Revision ID: 8233b43c5e0f
Revises: 01a030ccb3db
Create Date: 2025-03-31 14:37:37.184105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8233b43c5e0f'
down_revision = '01a030ccb3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifa_electrica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zonas_geograficas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifa_electrica', schema=None) as batch_op:
        batch_op.drop_column('zonas_geograficas')

    # ### end Alembic commands ###
