"""empty message

Revision ID: 973e507ca0fd
Revises: 88d24bf205f8
Create Date: 2025-03-03 23:35:31.551662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973e507ca0fd'
down_revision = '88d24bf205f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
