"""empty message

Revision ID: c7d4a8943dab
Revises: 
Create Date: 2025-03-02 08:44:20.753610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d4a8943dab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('confirm_password', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('birthday_date', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('birthday_date'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('price', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('laptops',
    sa.Column('laptop_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('pantalla', sa.String(length=150), nullable=False),
    sa.Column('procesador', sa.String(length=150), nullable=False),
    sa.Column('modelo_cpu', sa.String(length=150), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=150), nullable=False),
    sa.Column('memoria_ram', sa.String(length=150), nullable=False),
    sa.Column('almacenamiento', sa.String(length=300), nullable=False),
    sa.Column('camara', sa.String(length=150), nullable=False),
    sa.Column('bateria', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('tecnologia', sa.String(length=150), nullable=False),
    sa.Column('colores', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.PrimaryKeyConstraint('laptop_id')
    )
    op.create_table('smartphones',
    sa.Column('smartphone_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('pantalla', sa.String(length=150), nullable=False),
    sa.Column('procesador', sa.String(length=150), nullable=False),
    sa.Column('memoria_ram', sa.String(length=150), nullable=False),
    sa.Column('almacenamiento', sa.String(length=150), nullable=False),
    sa.Column('camara', sa.String(length=150), nullable=False),
    sa.Column('bateria', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('conectividad', sa.String(length=150), nullable=False),
    sa.Column('colores', sa.String(length=75), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.PrimaryKeyConstraint('smartphone_id')
    )
    op.create_table('tv',
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('contenido_de_la_caja', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('usos_recomendados', sa.String(length=150), nullable=False),
    sa.Column('año_modelo', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('pantalla', sa.String(length=150), nullable=False),
    sa.Column('conectividad', sa.String(length=150), nullable=False),
    sa.Column('medidas', sa.String(length=50), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.PrimaryKeyConstraint('tv_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv')
    op.drop_table('smartphones')
    op.drop_table('laptops')
    op.drop_table('cart')
    op.drop_table('user')
    # ### end Alembic commands ###
