"""empty message

Revision ID: cbab7e419875
Revises: ab49e7f6273b
Create Date: 2025-03-19 15:26:14.734156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbab7e419875'
down_revision = 'ab49e7f6273b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('proveedor_preferido_id_fk', sa.Integer(), nullable=False),
    sa.Column('rango_horario_fav', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_preferido_id_fk'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifa_electrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id_fk', sa.Integer(), nullable=False),
    sa.Column('registro_hora_fecha_tarifa', sa.DateTime(), nullable=False),
    sa.Column('precio_kw_hora', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('carbon_impact_kgCO', sa.Float(), nullable=False),
    sa.Column('nombre_tarifa', sa.String(length=100), nullable=False),
    sa.Column('rango_horario_bajo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id_fk'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('rango_horario', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id_fk', sa.Integer(), nullable=False),
    sa.Column('ahorro_estimado', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('recomienda_tarifa_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id_fk'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['recomienda_tarifa_id_fk'], ['tarifa_electrica.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('proveedor_actual_id_fk', sa.Integer(), nullable=False),
    sa.Column('tarifa_actual_id_fk', sa.Integer(), nullable=True),
    sa.Column('proveedor_nuevo_id_fk', sa.Integer(), nullable=False),
    sa.Column('tarifa_nueva_id_fk', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_actual_id_fk'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['proveedor_nuevo_id_fk'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['tarifa_actual_id_fk'], ['tarifa_electrica.id'], ),
    sa.ForeignKeyConstraint(['tarifa_nueva_id_fk'], ['tarifa_electrica.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_created')
        batch_op.drop_column('name')

    op.drop_table('solicitud_cambio')
    op.drop_table('recomendacion')
    op.drop_table('tarifa_electrica')
    op.drop_table('preferencia')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
