"""empty message

Revision ID: d4599d240edd
Revises: 973e507ca0fd
Create Date: 2025-03-04 00:44:59.805560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4599d240edd'
down_revision = '973e507ca0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('projects_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('projects_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
