"""Inicialización de la base de datos

Revision ID: f1cc659f7467
Revises: 
Create Date: 2025-02-27 23:42:10.245977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cc659f7467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birthdate'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('balance'),
    sa.UniqueConstraint('coin'),
    sa.UniqueConstraint('type')
    )
    op.create_table('account_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accounts_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('time', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['accounts_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount'),
    sa.UniqueConstraint('coin'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('time'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_details')
    op.drop_table('accounts')
    op.drop_table('user')
    # ### end Alembic commands ###
